Documents/Fiverr/TerryAmbinet/Cleansiness/Cleansiness/Controllers/AuthController.cs
using AutoMapper;
using Cleansiness.Helpers;
using Cleansiness.Shared.DTO;
using Cleansiness.Shared.Interfaces;
using Cleansiness.Shared.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Cleansiness.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthRepository _repo;
        public IConfiguration _config;
        private readonly IMapper _mapper;
        private readonly ICommonRepository _common;

        public AuthController(IAuthRepository repo, IConfiguration configuration, IMapper mapper,
            ICommonRepository common)
        {
            _mapper = mapper;
            _common = common;
            _config = configuration;
            _repo = repo;
        }
        public IActionResult Login()
        {
            ViewBag.Users = _common.GetAppUsers();
            return View(new UserForLoginDto { IsTriedForLogin = false });
        }

        [HttpPost]
        public IActionResult Login(UserForLoginDto pUserForLoginDto)
        {
            ViewBag.Users = _common.GetAppUsers();
            AppUser vAppUser = _repo.Login(pUserForLoginDto.UserName, pUserForLoginDto.Password);
            if (vAppUser != null)
            {
                if (vAppUser.UserStatus)
                {
                    string vAppUserContent = JsonConvert.SerializeObject(vAppUser, Formatting.Indented,
                    new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects });
                    HttpContext.Session.SetString(SessionHelper.UserId, vAppUser.UserId.ToString());
                    HttpContext.Session.SetString(SessionHelper.UserEmail, vAppUser.Email.ToString());
                    HttpContext.Session.SetString(SessionHelper.AppUser, vAppUserContent);
                    HttpContext.Session.SetString(SessionHelper.UserType, vAppUser.UserType.ToString());
                    HttpContext.Session.SetString(SessionHelper.UserName, vAppUser.UserName);
                    _common.LogUserActivity(vAppUser, 1);
                    return RedirectToAction("Dashboard", "Admin");
                }
                else
                {
                    return View(new UserForLoginDto { IsTriedForLogin = true });
                }
            }
            else
            {
                return View(new UserForLoginDto { IsTriedForLogin = true });
            }
        }

        [HttpGet]
        public IActionResult Logout()
        {
            if (!SessionHelper.IsLoggedIn(HttpContext))
                return RedirectToAction("login", "auth");
            var vAppUser = JsonConvert.DeserializeObject<AppUser>(HttpContext.Session.GetString(SessionHelper.AppUser));
            _common.LogUserActivity(vAppUser, 2);
            SessionHelper.DestroySession(HttpContext);
            return RedirectToAction("login", "auth");
        }
    }
}

Documents/Fiverr/TerryAmbinet/Cleansiness/Cleansiness/Controllers/HomeController.cs
using Cleansiness.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cleansiness.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Documents/Fiverr/TerryAmbinet/Cleansiness/Cleansiness/Views/Shared/_Footer.cshtml
<div class="footertopmargin">
    <!--Footer-->
    <footer id="footer" class="container-fluid fixed-bottom">
        <div class="container p-0">
            <div class="row py-0">
                <div class="col-md-6 text-left">
                    <i class="fas fa-user color-mygreen pr-2"></i> All Users
                    <i class="fas fa-hospital-alt color-mygreen pl-4 pr-2"></i>The Wirral Teaching Hospital
                </div>
                <div class="col-md-6 text-lg-right">
                    <a href="auditactivity.html"><i class="fas fa-user color-mygreen pl-4 pr-2"></i>Activity Log</a>
                    <a href="login.html"><i class="fas fa-sign-out-alt color-mygreen pl-4 pr-2"></i>Logout</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->
</div>

Documents/Fiverr/TerryAmbinet/Cleansiness/Cleansiness/Views/Shared/_Home.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="NHS Hospital Cleansiness Monitor" name="description">
    <meta content="NHS, Hospital, Cleansiness Monitor" name="keywords">
    <!-- Favicons -->
    <link href="~/images/favicon.png" rel="icon">

    <!-- Vendor CSS Files -->
    <link href="~/cssjs/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">

    <!-- Vendor CSS Files -->
    <link href="~/cssjs/bootstrap.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/cssjs/ctuadim.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">

    <title>@ViewData["Title"] - Cleanliness</title>
</head>
<body class="bg-white">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/bootstrap-select.min.js"></script>
    <script src="~/cssjs/dp-datepicker.js"></script>
    <script src="~/cssjs/dp-main.js"></script>
    
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Documents/Fiverr/TerryAmbinet/Cleansiness/Cleansiness/Views/Shared/_Layout.cshtml
@using Cleansiness.Helpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="NHS Hospital Cleansiness Monitor" name="description">
    <meta content="NHS, Hospital, Cleansiness Monitor" name="keywords">
    <!-- Favicons -->
    <link href="~/images/favicon.png" rel="icon">

    <script src="~/jquery/jquery.min.js"></script>
    <!-- Vendor CSS Files -->
    <link href="~/cssjs/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">

    <!-- Vendor CSS Files -->
    <link href="~/cssjs/bootstrap.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/cssjs/ctuadim.css" rel="stylesheet">

    <link href="~/cssjs/dp-main.css" rel="stylesheet">
    <link href="~/cssjs/dp-datepicker.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">

    <title>@ViewData["Title"] - Cleanliness</title>
</head>
<body class="bg-white">

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="footertopmargin">
    <!--Footer-->
    <footer id="footer" class="container-fluid fixed-bottom">
        <div class="container p-0">
            <div class="row py-0">
                <div class="col-md-6 text-left">
                    @*<a asp-controller="Admin" asp-action="AllUsers">
                        
                    </a>*@
                    <i class="fas fa-user color-mygreen pr-2"></i> @Context.Session.GetString(SessionHelper.UserName) @*All Users*@
                    
                    <i class="fas fa-hospital-alt color-mygreen pl-4 pr-2"></i>The Wirral Teaching Hospital
                </div>
                <div class="col-md-6 text-lg-right">
                    <a asp-controller="admin" asp-action="ActivityLogs">
                        <i class="fas fa-user color-mygreen pl-4 pr-2"></i>Activity Log</a>
                    <a asp-controller="Auth" asp-action="Logout">
                        <i class="fas fa-sign-out-alt color-mygreen pl-4 pr-2"></i>Logout</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->
</div>

    <!-- Vendor JS Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/bootstrap-select.min.js"></script>
    <script src="~/cssjs/dp-datepicker.js"></script>
    <script src="~/cssjs/dp-main.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Documents/Fiverr/TerryAmbinet/Cleansiness/Cleansiness/Views/Shared/_Topbar.cshtml
<!-- Top bar Start -->
<div class="container bg-myblue my-4 rounded">
    <div class="row px-2 py-3">
        <div class="col-sm-12 text-center">
            <a asp-controller="Auth" asp-action="Login"><img src="../images/logowt.png" alt="logo"></a>
        </div>
    </div>
</div>
<!-- Top bar end -->